version: '3.9'

services:
  server:
    container_name: server
    build:
      context: ./server
      dockerfile: Dockerfile
    command: yarn distribute
  bot:
    container_name: bot
    build: 
      context: ./bot
      dockerfile: Dockerfile
    command: yarn distribute