version: '3.7'

services:
  server:
    container_name: server
    build:
      context: ./server
      dockerfile: Dockerfile
    env_file: ./server/.env
    ports:
      - 1337:1337
    command: yarn distribute
  bot:
    container_name: bot
    build: 
      context: ./bot
      dockerfile: Dockerfile
    command: yarn distribute